name: delivoostores
description: A new Flutter application.

version: 1.5.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_phoenix: ^0.1.0
  country_code_picker: ^1.3.15
  grouped_buttons: ^1.0.4
  google_fonts: ^1.1.0
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9



flutter:
  uses-material-design: true
  assets:
    - images/
    - images/account/
    - images/address/
    - images/custom/
    - images/footermenu/
    - images/icons/
    - images/logos/
    - images/veg/
    - images/veg/Sellers/
    - images/veg/Vegetables/